In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<font size="6" color="red">ch11. 데이터 프레임과 시리즈(Pandas)</font>
- pip install pandas (아나콘다 프롬프트)

# 판타스 패키지
- 데이터 분석을 위해 반드시 알아야할 패키지. 넘파이를 기반으로 하며, 다른 많은 라이브러리와 잘 통합되도록 설계
- 1차원 구조를 갖는 시리즈 / 2차원 구조를 갖는 데이터 프레임을 제공
- 판다스 장점 : 데이터 프레임 생성, 파일 i/o, 레이블링, 부분데이터추출, 크기변경(행이나 열삽입 삭제),
    데이터 분할, 병합, 데이퍼 정렬, 결측치 처리, 피벗과 언피벗 등이 용이
- https://pandas.pydata.org/docs/reference/index.html(API reference)

In [16]:
import pandas as pd
pd.__version__

'1.5.3'

In [17]:
data = pd.read_json('data/ch09_member1.json'
                   # , encoding='utf-8' 판다스 read함수의 기본 encoding은 utf-8
                   )
display(data)
print(type(data))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 20: invalid start byte

In [15]:
member4 = pd.read_csv('data/ch09_member4.csv') # 해더가 있는 csv
member4

  name  age             email   address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구

In [12]:
member1 = pd.read_csv('data/ch09_member1.csv',
                      header=None,
                      names=['name','age','email','주소'])
member1

  name  age             email        주소
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구

In [13]:
pd.read_hdf('data/ch09_iris.h5', key="iris")

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# 데이터 프레임 만들기
## 딕셔너리를 이용해서 데이터 프레임 만들기

In [19]:
d = {'kor':[100,90], 'mat':[95,99]}
df = pd.DataFrame(data=d)
df

   kor  mat
0  100   95
1   90   99

In [20]:
df.to_dict() # 데이터프레임을 딕셔너리로

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 99}}

In [21]:
df.to_numpy() # 데이터프레임을 넘파이배열

array([[100,  95],
       [ 90,  99]], dtype=int64)

In [25]:
d = [{'kor':100, 'mat':95.0},
     {'kor':90, 'mat':99}]
df = pd.DataFrame(d) # 데이터 프레임의 열은 동일 자료형
df

   kor   mat
0  100  95.0
1   90  99.0

In [27]:
df.dtypes # 데이터 프레임의 열별 타입

kor      int64
mat    float64
dtype: object

In [28]:
df.info() #★ 많이 씀

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 160.0 bytes

In [32]:
type(df['kor']) # 시리즈 1차원데이터

pandas.core.series.Series

In [35]:
import numpy as np
df['kor']= df['kor'].astype(np.float64) # 데이터프레임의 열 타입 변경
df

     kor   mat
0  100.0  95.0
1   90.0  99.0

In [36]:
d = [{'kor':100, 'mat':100},
     {'kor':90, 'mat':99},
     {'kor':83, 'eng':85}]
df = pd.DataFrame(data=d)
df

   kor    mat   eng
0  100  100.0   NaN
1   90   99.0   NaN
2   83    NaN  85.0

In [37]:
type(np.nan) # 결측치의 타입 : float

float

In [39]:
# 결측치는 int로 형변환 불가

## 리스트를 이용해 데이터프레임 만들기

In [40]:
kor = [100, 90, 80, 70, 60]
mat = [100, 90, 81, 71, 61]
df = pd.DataFrame({'kor':kor, 'mat':mat})
df

   kor  mat
0  100  100
1   90   90
2   80   81
3   70   71
4   60   61

In [41]:
pd.DataFrame(np.c_[kor, mat], columns=['kor','mat'])

   kor  mat
0  100  100
1   90   90
2   80   81
3   70   71
4   60   61

In [43]:
l = [[100, 90], [70,80]]
pd.DataFrame(l, columns=['국어', '수학'])

    국어  수학
0  100  90
1   70  80

- data.go.kr에서 "상가상권 정보" 다운 / "민간 아파트 분양가격" 다운로드

In [48]:
 %ls C:\ai\downloads\shareData\상가정보\

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 0C81-36F7

 C:\ai\downloads\shareData\상가정보 디렉터리

2026-07-14  오후 05:39    <DIR>          .
2026-07-14  오후 05:39    <DIR>          ..
2025-11-03  오전 12:45             1,011 [필독]파일열람방법.txt
2026-04-27  오전 11:10        61,321,696 소상공인시장진흥공단_상가(상권)정보_강원_202603.csv
2026-04-27  오전 11:10       367,852,181 소상공인시장진흥공단_상가(상권)정보_경기_202603.csv
2026-04-27  오전 11:10        92,474,293 소상공인시장진흥공단_상가(상권)정보_경남_202603.csv
2026-04-27  오전 11:10        76,309,810 소상공인시장진흥공단_상가(상권)정보_경북_202603.csv
2026-04-27  오전 11:10        40,031,721 소상공인시장진흥공단_상가(상권)정보_광주_202603.csv
2026-04-27  오전 11:10        61,825,564 소상공인시장진흥공단_상가(상권)정보_대구_202603.csv
2026-04-27  오전 11:10        41,866,930 소상공인시장진흥공단_상가(상권)정보_대전_202603.csv
2026-04-27  오전 11:10        84,329,596 소상공인시장진흥공단_상가(상권)정보_부산_202603.csv
2026-04-27  오전 11:10       292,646,735 소상공인시장진흥공단_상가(상권)정보_서울_202603.csv
2026-04-27  오전 11:10         9,651,297 소상공인시장진흥공단_상가(상권)정보_세종_202603.csv
2026-04-27  오전 11:10        28,285,232 소상공인시장진흥공단_상가(상권)정보_울산_202603.csv
2026-04-27  오전 11:10        74,007,608 소상공인시장진흥공단_상가(상권)정보_인천_202603.csv
2026-04-27  오전 11:10        53,165,985 소상공인시장진흥공단_상가(상권)정보_전남_202603.csv
2026-04-27  오전 11:10        56,632,709 소상공인시장진흥공단_상가(상권)정보_전북_202603.csv
2026-04-27  오전 11:10        32,746,698 소상공인시장진흥공단_상가(상권)정보_제주_202603.csv
2026-04-27  오전 11:10        66,764,669 소상공인시장진흥공단_상가(상권)정보_충남_202603.csv
2026-04-27  오전 11:10        50,941,247 소상공인시장진흥공단_상가(상권)정보_충북_202603.csv
              18개 파일       1,490,854,982 바이트
               2개 디렉터리  148,746,321,920 바이트 남음

In [58]:
df = pd.read_csv(r'c:\ai\downloads\shareData\상가정보\소상공인시장진흥공단_상가(상권)정보_세종_202603.csv',
                # encoding='utf-8', sep=',',
                 nrows=30, # 처음 30행만 가져오기
                 low_memory=False, # 데이터 용량이 클 경우 기입
                )
df.shape # 30행 39열

(30, 39)

In [59]:
df.head(1) # 상위 1행

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220813963449,레인카페,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,기타 비알코올 음료점업,36,세종특별자치시,36110,세종특별자치시,36110250,조치원읍,3611025021,조치원읍,3611025021101010001,1,대지,101,1.0,세종특별자치시 세종특별자치시 조치원읍 원리 101-1,361104574473,세종특별자치시 세종특별자치시 조치원읍 조치원8길,16,NaN,4473025021101010001038753,NaN,세종특별자치시 세종특별자치시 조치원읍 조치원8길 16,339883.0,30027,NaN,지,NaN,127.300453,36.600906

In [60]:
# 판다스 디스플레이스 옵션
pd.options.display.max_columns = 39 # 39행까지 display
pd.options.display.max_rows = 40 # 40행까지 display

In [57]:
df.head(2).T

                                       0                                1
상가업소번호              MA010120220813963449             MA010120220805872513
상호명                                 레인카페                             수와마을
지점명                                  NaN                              NaN
상권업종대분류코드                             I2                               I2
상권업종대분류명                              음식                               음식
상권업종중분류코드                           I212                             I201
상권업종중분류명                           비알코올                                한식
상권업종소분류코드                         I21201                           I20101
상권업종소분류명                              카페                           백반/한정식
표준산업분류코드                          I56229                           I56111
표준산업분류명                     기타 비알코올 음료점업                       한식 일반 음식점업
시도코드                                  36                               36
시도명                              세종특별자치시                          세종특별자치시
시군구코드                              36110                            36110
시군구명                             세종특별자치시                          세종특별자치시
행정동코드                           36110250                         36110250
행정동명                                조치원읍                             조치원읍
법정동코드                         3611025021                       3611025030
법정동명                                조치원읍                             조치원읍
지번코드                 3611025021101010001              3611025030103790016
대지구분코드                                 1                                1
대지구분명                                 대지                               대지
지번본번지                              101.0                            379.0
지번부번지                                1.0                             16.0
지번주소       세종특별자치시 세종특별자치시 조치원읍 원리 101-1  세종특별자치시 세종특별자치시 조치원읍 죽림리 379-16
도로명코드                       361104574473                     361103258034
도로명           세종특별자치시 세종특별자치시 조치원읍 조치원8길         세종특별자치시 세종특별자치시 조치원읍 충현로
건물본번지                                 16                               75
건물부번지                                NaN                              1.0
건물관리번호         4473025021101010001038753        4473025030103790016042253
건물명                                  NaN                              NaN
도로명주소      세종특별자치시 세종특별자치시 조치원읍 조치원8길 16    세종특별자치시 세종특별자치시 조치원읍 충현로 75-1
구우편번호                           339883.0                         339884.0
신우편번호                              30027                            30034
동정보                                  NaN                              NaN
층정보                                    지                              NaN
호정보                                  NaN                              NaN
경도                            127.300453                       127.296263
위도                             36.600906                        36.595303

## read_csv

In [2]:
# (1) csv 파일 불러오기(기본값)
import pandas as pd
member = pd.read_csv("data/ch11_member.csv")
member

   Name  Age          Email  Address       Birth
0   홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1   홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2   홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3   홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4   홍길중   23   mid@hong.com   부산시 중구  1999-01-30
5  #홍길뜽   24    non@not.com      없는구  2000-01-01

In [5]:
member.info() # ★

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      6 non-null      int64
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int64(1), object(4)
memory usage: 368.0+ bytes

In [7]:
# 문자형으로 변환 제일 안쓴다네요
member['Age'] = member['Age'].astype('str')
member['Age'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 6 entries, 0 to 5
Series name: Age
Non-Null Count  Dtype
--------------  -----
6 non-null      object
dtypes: object(1)
memory usage: 176.0+ bytes

In [32]:
# 숫자형으로 변환
import numpy as np
member['Age'].astype('int16') # float로 바꿀때
member['Age'].astype(np.int16)
pd.to_numeric(member['Age'],
              downcast='integer', # 빼면 int32나 float64로 자동변환
              errors='coerce') # 숫자로 바꿀 수 없는 데이터는 결측치로 변환 ex) 3,000

0    20
1    30
2    21
3    22
4    23
5    24
Name: Age, dtype: int8

In [25]:
# 문자로 읽어들인 Birth를 datatime형으로
member['Birth'] = member['Birth'].astype('datetime64[ns]') #1999-01-01
member = member.astype({'Birth':'datetime64[ns]', 'Age':'int32'})
# 01-01-1999, 19990101
member['Birth'] = pd.to_datetime(member['Birth'],
              #format='%Y-%m-%d %H:%M:%S'
              )
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      6 non-null      int32
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int32(1), object(3)
memory usage: 344.0+ bytes

In [30]:
member['year'] = member.Birth.dt.year
member['month'] = member.Birth.dt.month
member['day'] = member.Birth.dt.day

In [31]:
member

   Name  Age          Email  Address      Birth  year  month  day
0   홍길동   20  hong@hong.com  서울시 강동구 1999-01-01  1999      1    1
1   홍길서   30   seo@hong.com   서울시 중구 1999-12-01  1999     12    1
2   홍길남   21   nam@hong.com  서울시 강동구 1999-11-01  1999     11    1
3   홍길북   22   buk@hong.com  서울시 관악구 1999-05-01  1999      5    1
4   홍길중   23   mid@hong.com   부산시 중구 1999-01-30  1999      1   30
5  #홍길뜽   24    non@not.com      없는구 2000-01-01  2000      1    1

In [33]:
current_date = pd.to_datetime('2026-07-15')
member['일수'] = (current_date - member.Birth).dt.days
member

   Name  Age          Email  Address      Birth  year  month  day     일수
0   홍길동   20  hong@hong.com  서울시 강동구 1999-01-01  1999      1    1  10057
1   홍길서   30   seo@hong.com   서울시 중구 1999-12-01  1999     12    1   9723
2   홍길남   21   nam@hong.com  서울시 강동구 1999-11-01  1999     11    1   9753
3   홍길북   22   buk@hong.com  서울시 관악구 1999-05-01  1999      5    1   9937
4   홍길중   23   mid@hong.com   부산시 중구 1999-01-30  1999      1   30  10028
5  #홍길뜽   24    non@not.com      없는구 2000-01-01  2000      1    1   9692

In [35]:
# (2) 특정행을 제외하고 cp949 encoding 파일 읽어오기
member = pd.read_csv('data/ch11_membercp949.csv',
                    encoding='cp949',
                    skiprows=[1, 6]) # 1, 6행 제외하고 읽어오기
member

  Name  Age         Email  Address       Birth
0  홍길서   30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남   21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북   22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중   23  mid@hong.com   부산시 중구  1999-01-30

In [38]:
# (3) sep='|', 주석(#) 제외, 상위 몇 행만, datetime형 필드지정
member_df = pd.read_csv('data/ch11_membersep.csv',
                       sep='|',               # | 기준으로 데이터를 분리해서 읽기
                       comment='#',           # #(주석)이 있는 행은 제외하고 읽기
                       nrows=3,               # 상위 3행만 읽기
                       parse_dates=['Birth']) # datetime형으로 읽어올 필드지정
member_df

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [37]:
member_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     3 non-null      object
 1   Age      3 non-null      int64
 2   Email    3 non-null      object
 3   Address  3 non-null      object
 4   Birth    3 non-null      object
dtypes: int64(1), object(4)
memory usage: 248.0+ bytes

In [40]:
member_df = pd.read_csv('data/ch11_membertab.csv',
                       sep='\t',
                       comment='#',
                       parse_dates=['Birth'])
member_df

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

## 패키지에서 가져오기 iris데이터
- iris가져오기 방법1 : sklearn(머신러닝 패키지)
- iris가져오기 방법2 : statsmodels (R 데이터)
- iris가져오기 방법3 : seaborn(시각화 패지키)

### iris방법 1 : sklearn
- sklearn.datasets 모듈 데이터(iris)를 데이터프레임으로 변환

In [48]:
from sklearn import datasets
# import sklearn.datasetse as datasets : 머신러닝을 공부하기 위한 학습용 데이터셋을 제공
# sklearn 패키지의 데이터셋 : 독립변수(입력변수)와 종속변수(타겟변수)가 분리된 딕셔너리 형태 제공
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [43]:
iris.data #독립변수
iris['data'][:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [44]:
pd.DataFrame(iris.data)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [50]:
iris.feature_names # 독립변수의 열이름
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [54]:
# 데이터프레임에서 열이름
[ col[:-5].replace(' ', '_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [55]:
[ col[:12].strip().replace(' ', '_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [57]:
# 종속변수(타겟변수)
iris.target
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [58]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [59]:
# 데이터프레임에 가장 오른쪽 열(타겟변수-species)
iris.target_names[iris.target]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica'], dtype='<U10')

In [63]:
# 독립변수 [ col[:-5].replace(' ', '_') for col in iris.feature_names]
data = iris.data
print(data[::50])
# 종속변수
target = iris.target_names[iris.target].reshape(-1, 1)
print(target[::50])

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]
[['setosa']
 ['versicolor']
 ['virginica']]

In [64]:
print('독립변수의 차원 :', data.shape)
print('종속변수의 차원 :', target.shape)

독립변수의 차원 : (150, 4)
종속변수의 차원 : (150, 1)

In [66]:
# ⓐ 독립변수, 종속변수를 stack한 후, 데이터프레임으로 생성
import numpy as np
df = pd.DataFrame(np.hstack( (data, target) ),
                 columns=[col[:-5].replace(' ', '_') for col in iris.feature_names] + ['species'])
df.head() # 상위 5행만

  sepal_length sepal_width petal_length petal_width species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [69]:
df['petal_width']
df.petal_width[:3]

0    0.2
1    0.2
2    0.2
Name: petal_width, dtype: object

In [72]:
import numpy as np
df = pd.DataFrame(np.hstack( (data, target) ),
                 columns=iris.feature_names + ['species'])
df.head(3)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa

In [74]:
df['petal width (cm)'][:3]
#df.petal width (cm)

0    0.2
1    0.2
2    0.2
Name: petal width (cm), dtype: object

In [75]:
# ⓑ 독립변수, 종속변수를 따로 데이터프레임으로 생성한 후 두 데이터프레임을 연결
# X : 독립변수 데이터프레임
X = pd.DataFrame(data,
                columns=[col[:-5].replace(' ', '_') for col in iris.feature_names])
X.head(1)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

In [76]:
# y : 종속변수 데이터프레임
y = pd.DataFrame(target, columns=['species'])
y.tail() # 하위 5줄 출력

       species
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

In [77]:
print(X.index) # index:행이름
print(y.index)

RangeIndex(start=0, stop=150, step=1)
RangeIndex(start=0, stop=150, step=1)

In [78]:
# 두 데이터 프레임을 연결(열로 연결)
iris_df = pd.concat([X, y], axis=1)

In [79]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

### iris방법2 : statsmodels

In [83]:
from statsmodels.api import datasets
iris_dataset = datasets.get_rdataset('iris',
                                    package='datasets',
                                    cache=True) # 데이터를 PC에 저장 (~/statsmodels)
iris_dataset

In [84]:
iris = iris_dataset.data
iris.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [85]:
iris['Sepal.Length'][:3]
# iris.Sepal.Length 불가

0    5.1
1    4.9
2    4.7
Name: Sepal.Length, dtype: float64

In [86]:
# 열 이름 수정
[col.replace('.','_').lower() for col in iris.columns]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [87]:
iris.columns = [col.replace('.','_').lower() for col in iris.columns]
iris.head(1)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

### iris방법3 : seaborn

In [88]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head(1)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [91]:
# 데이터프레임을 파일로 출력
iris.to_csv('data/ch11_iris.csv', # 4.01KB
           #sep=',',
           #encoding='utf-8',
           index=False) # 행이름이 생략되서 파일 출력

In [92]:
iris.to_csv('data/ch11_iris.gz', # 885B
           index=False,
           compression='infer') # 파일 확장자(.zip, .gz, bz2등)를 보고 자동으로 압축형식을 추론해서 압축

In [93]:
load_iris = pd.read_csv('data/ch11_iris.csv')
load_iris.sample(3) # 임의로 3개

     sepal_length  sepal_width  petal_length  petal_width    species
10            5.4          3.7           1.5          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
149           5.9          3.0           5.1          1.8  virginica

In [94]:
load_iris = pd.read_csv('data/ch11_iris.gz', compression='infer')
load_iris.sample(3)

    sepal_length  sepal_width  petal_length  petal_width     species
83           6.0          2.7           5.1          1.6  versicolor
85           6.0          3.4           4.5          1.6  versicolor
20           5.4          3.4           1.7          0.2      setosa

# 이름(열, 행) 지정하기
## 열이름 지정하기

In [95]:
member = pd.read_csv('data/ch11_member.csv', comment='#', parse_dates=['Birth'])
member

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [96]:
member.columns # 열이름

Index(['Name', 'Age', 'Email', 'Address', 'Birth'], dtype='object')

In [102]:
member.columns = ['이름', '나이', '메일','주소','생년월일']
member

    이름  나이             메일       주소       생년월일
동  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
동  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

## 행이름 지정하기

In [97]:
member.index # 행이름

RangeIndex(start=0, stop=5, step=1)

In [98]:
member.index = range(10, 15)
member

   Name  Age          Email  Address      Birth
10  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
11  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
12  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
13  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
14  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [100]:
member.index = ['동','서','남','북','동']
member

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
동  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [103]:
member['이름']

동    홍길동
서    홍길서
남    홍길남
북    홍길북
동    홍길중
Name: 이름, dtype: object

In [105]:
member.loc['서', '이름'] #loc[행이름, 열이름]으로 부분 데이터 조회(4절)

'홍길서'

In [106]:
member

    이름  나이             메일       주소       생년월일
동  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
동  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [107]:
print(member.index)
print(member.index.name) # 행이름들의 이름이 없음

Index(['동', '서', '남', '북', '동'], dtype='object')
None

In [109]:
# 이름을 행이름으로 (실행결과가 출력되서 나오면 return될뿐, member가 안바뀜)
# member를 이름열을 행이름으로 수정 (1)할당 (2) inplace매개변수에 True(기본값은 False)
member.set_index('이름', inplace=True)

In [110]:
member

     나이             메일       주소       생년월일
이름
홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
홍길서  30   seo@hong.com   서울시 중구 1999-12-01
홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [111]:
print(member.index)
print(member.index.name)
print(member.columns)

Index(['홍길동', '홍길서', '홍길남', '홍길북', '홍길중'], dtype='object', name='이름')
이름
Index(['나이', '메일', '주소', '생년월일'], dtype='object')

In [113]:
# 인덱스를 열에 편입시키기
# member
member = member.reset_index()

In [114]:
member.index = [0,4,1,2,3]
member

    이름  나이             메일       주소       생년월일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
4  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
1  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
2  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
3  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [116]:
# 기본 index를 0부터 새롭게 다시 numbering (비추)
member.index = range(len(member)) # 비추

In [117]:
member.index = [99,77,88,66,33]
# 기존 index를 새로운 열에 편입시키지않고 제거 후 숫자 index를 초기화(추천)
member.reset_index(drop=True, inplace=True) #추천~

In [118]:
member

    이름  나이             메일       주소       생년월일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

## 레벨 이름 지정하기

In [119]:
print(member.columns)
print(member.columns.name)
display(member)

Index(['이름', '나이', '메일', '주소', '생년월일'], dtype='object')
None

    이름  나이             메일       주소       생년월일
0  홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [120]:
member.columns.name = '컬럼명'
member

컬럼명   이름  나이             메일       주소       생년월일
0    홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1    홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2    홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3    홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4    홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [121]:
member.columns = [['기본정보','기본정보','기본정보','추가정보','추가정보'],
                  ['이름',    '나이',   '메일',   '주소',    '생년월일']]
member.columns.names = ['대분류','소분류']
member

대분류 기본정보                        추가정보
소분류   이름  나이             메일       주소       생년월일
0    홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
1    홍길서  30   seo@hong.com   서울시 중구 1999-12-01
2    홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
3    홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
4    홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [122]:
member.index = [['좌우','좌우', '상하','상하','상하'],
                ['동', '서',    '남',  '북',  '중']]
member.index.names = ['레벨1', '레벨2']
member

대분류     기본정보                        추가정보
소분류       이름  나이             메일       주소       생년월일
레벨1 레벨2
좌우  동    홍길동  20  hong@hong.com  서울시 강동구 1999-01-01
    서    홍길서  30   seo@hong.com   서울시 중구 1999-12-01
상하  남    홍길남  21   nam@hong.com  서울시 강동구 1999-11-01
    북    홍길북  22   buk@hong.com  서울시 관악구 1999-05-01
    중    홍길중  23   mid@hong.com   부산시 중구 1999-01-30

In [123]:
member[('기본정보','이름')]

레벨1  레벨2
좌우   동      홍길동
     서      홍길서
상하   남      홍길남
     북      홍길북
     중      홍길중
Name: (기본정보, 이름), dtype: object

In [124]:
member.loc['상하']

대분류 기본정보                       추가정보
소분류   이름  나이            메일       주소       생년월일
레벨2
남    홍길남  21  nam@hong.com  서울시 강동구 1999-11-01
북    홍길북  22  buk@hong.com  서울시 관악구 1999-05-01
중    홍길중  23  mid@hong.com   부산시 중구 1999-01-30

In [125]:
member.loc[('상하', '남'), ('기본정보', '이름')]

'홍길남'

In [126]:
member.xs(key='남', level='레벨2')

대분류 기본정보                       추가정보
소분류   이름  나이            메일       주소       생년월일
레벨1
상하   홍길남  21  nam@hong.com  서울시 강동구 1999-11-01

In [ ]:
member.loc['좌우', '기본정보']

# 부분 데이터 조회

In [129]:
member = pd.read_csv('data/ch11_member.csv', comment='#', parse_dates=['Birth'])
member

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

## 열 조회
- df[열이름]
- df[조건]
- df[열이름들]

In [130]:
member['Name']
member.Name

0    홍길동
1    홍길서
2    홍길남
3    홍길북
4    홍길중
Name: Name, dtype: object

In [132]:
member[ ['Name','Age', 'Birth'] ] #list형태로

  Name  Age      Birth
0  홍길동   20 1999-01-01
1  홍길서   30 1999-12-01
2  홍길남   21 1999-11-01
3  홍길북   22 1999-05-01
4  홍길중   23 1999-01-30

In [ ]:
# member[0] : 행이르믕로 조회할 경우 loc사용

## loc을 이용한 조회
- df.loc[행이름, 열이름] : 행이름과 열이름으로 조회
    * 행이름과 열이름 자리에 슬라이싱(from:to)은 from부터 to까지(to포함)
    * 행이름과 열이름 자리에 list 가능
    * 열이름 생략시 모든 열 조회
    * 행이름은 생략 불가능

In [136]:
member.loc[0:2] # 0행부터 2행까지
member.loc[0:2,]
member.loc[0:2, :]
member.loc[0:2, ...]
# 모든 열을 다 출력할 경우 생략 가능

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [138]:
member.index = ['동', '서', '남', '북', '중']
member.loc['동':'남']

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [139]:
# 동~남행까지 Name~Email
member.loc['동':'남', 'Name':'Email']

  Name  Age          Email
동  홍길동   20  hong@hong.com
서  홍길서   30   seo@hong.com
남  홍길남   21   nam@hong.com

In [140]:
# 동행과 남행만 조회
member.loc[['동', '남']]

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [142]:
# 동행과 남행의 Name과 Email만 조회
member.loc[['동', '남'], ['Name', 'Email']]

  Name          Email
동  홍길동  hong@hong.com
남  홍길남   nam@hong.com

In [145]:
# 모든 행의 Name열만
member.loc[:,'Name'] # 한열이나 한행은 결과가 1차원 시리즈
member.loc[...,'Name']

동    홍길동
서    홍길서
남    홍길남
북    홍길북
중    홍길중
Name: Name, dtype: object

In [146]:
member.loc['동']

Name                       홍길동
Age                         20
Email            hong@hong.com
Address                서울시 강동구
Birth      1999-01-01 00:00:00
Name: 동, dtype: object

In [148]:
type(member.loc['동']), type(member.loc[:, 'Name'])

(pandas.core.series.Series, pandas.core.series.Series)

## iloc을 이용한 조회
- df.iloc[행번호, 열번호]
    * 행번호, 열번호 자리에는 list, 슬라이싱[from:stop:by] : from부터 stop앞까지 by씩
- 열번호 생략시 모든 열 조회

In [149]:
member

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [165]:
# 2번째~3번째 행 (0이 처음)
member.loc['남':'북']
member.iloc[2:4]

  Name  Age         Email  Address      Birth
남  홍길남   21  nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22  buk@hong.com  서울시 관악구 1999-05-01

In [163]:
member.iloc[0] # 1차원 시리즈

Name                       홍길동
Age                         20
Email            hong@hong.com
Address                서울시 강동구
Birth      1999-01-01 00:00:00
Name: 동, dtype: object

In [164]:
# 0번째 ~ 2번째행, 1번째~2번째열
member.iloc[0:3, 1:3]

   Age          Email
동   20  hong@hong.com
서   30   seo@hong.com
남   21   nam@hong.com

In [151]:
# 0번째행과2번째행, 1번째열과 3번째열
member.iloc[[0,2],[1,3]]

   Age  Address
동   20  서울시 강동구
남   21  서울시 강동구

In [153]:
# 짝수번째행(0,2,4,번째)의 맨 마지막열을 제외하고 조회
member.iloc[::2, :-1]

  Name  Age          Email  Address
동  홍길동   20  hong@hong.com  서울시 강동구
남  홍길남   21   nam@hong.com  서울시 강동구
중  홍길중   23   mid@hong.com   부산시 중구

In [158]:
# 마지막행부터 처음행까지 거꾸로 출력
member.iloc[::-1]

  Name  Age          Email  Address      Birth
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

## 조건으로 조회

In [159]:
member

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
중  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [160]:
member['Age']>=23

동    False
서     True
남    False
북    False
중     True
Name: Age, dtype: bool

In [161]:
member.loc[[False, True, False, False, True]]

  Name  Age         Email Address      Birth
서  홍길서   30  seo@hong.com  서울시 중구 1999-12-01
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [162]:
# 23세 이상의 데이터만 조회 (아래 모두 동일한 결과)
member.loc[member['Age']>=23]
member.loc[member['Age']>=23, :]
member[member['Age']>=23]

  Name  Age         Email Address      Birth
서  홍길서   30  seo@hong.com  서울시 중구 1999-12-01
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [166]:
# 23세 이상의 데이터 중 Name, Age, Email
member.loc[member['Age']>=23, 'Name':'Email']

  Name  Age         Email
서  홍길서   30  seo@hong.com
중  홍길중   23  mid@hong.com

In [167]:
# 23세 이상의 데이터 중 Name, Email
member.loc[member['Age']>=23, ['Name','Email']]

  Name         Email
서  홍길서  seo@hong.com
중  홍길중  mid@hong.com

In [168]:
# 23세 이상인 아닌 데이터(모든 열) : ~ (반대)
member[~(member['Age']>=23)]

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01

In [172]:
# 관악구가 포함되어 있는지
address = '서울시 관악구 신림동'
print(address.find('관악구')!=-1) 
print(address.find('중구')!=-1) 
# 서울시로 시작되는지
print(address.startswith('서울시'))

True
False
True

In [174]:
# member['Address'].find('중구') # 시리즈에 문자함수를 바로 사용 x

※ 시리즈에 문자함수를 쓰기 위한 참조 : https://pandas.pydata.org/pandas-docs/stable/reference/series.html#string-handling

In [177]:
member['Address'].str.find('중구')!=-1

동    False
서     True
남    False
북    False
중     True
Name: Address, dtype: bool

In [181]:
# Address에 중구가 포함된 데이터
member[member['Address'].str.find('중구')!=-1]
member.loc[member['Address'].str.find('중구')!=-1]
member.loc[member['Address'].str.find('중구')!=-1, :]

  Name  Age         Email Address      Birth
서  홍길서   30  seo@hong.com  서울시 중구 1999-12-01
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [185]:
# Address에 중구가 포함된 데이터의 Name, Age, Email
member.loc[member['Address'].str.find('중구')!=-1, 'Name':'Email']
member.loc[member['Address'].str.find('중구')!=-1, ['Name','Age','Email']]

  Name  Age         Email
서  홍길서   30  seo@hong.com
중  홍길중   23  mid@hong.com

In [210]:
# Address에 중구가 포함된 데이터
member.loc[member['Address'].str.contains('중구')]

  Name  Age         Email Address      Birth
1  홍길서   30  seo@hong.com  서울시 중구 1999-12-01
4  홍길중   23           NaN  부산시 중구 1999-01-30

In [211]:
# Address가 중구이거나 관악구인 데이터
member[member['Address'].str.contains('중구|관악구')]

  Name  Age         Email  Address      Birth
1  홍길서   30  seo@hong.com   서울시 중구 1999-12-01
3  홍길북   22  buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23           NaN   부산시 중구 1999-01-30

In [187]:
# Address가 서울이 아닌 데이터
member[~member['Address'].str.startswith('서울')]

  Name  Age         Email Address      Birth
중  홍길중   23  mid@hong.com  부산시 중구 1999-01-30

In [194]:
# Name이 홍길동이거나 홍길남이거나 홍길서인 데이터의 모든 열 출력
member[(member['Name']=='홍길동')|(member['Name']=='홍길남')|(member['Name']=='홍길서')]
member[member["Name"].isin(['홍길동', '홍길남', '홍길서'])]

  Name  Age          Email  Address      Birth
동  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01

In [196]:
# Name이 홍길동이거나 홍길남이거나 홍길서인 데이터의 Name, Age, Email
member.loc[member["Name"].isin(['홍길동', '홍길남', '홍길서']), 'Name':'Email']
member.loc[member["Name"].isin(['홍길동', '홍길남', '홍길서']), ['Name','Age','Email']]

  Name  Age          Email
동  홍길동   20  hong@hong.com
서  홍길서   30   seo@hong.com
남  홍길남   21   nam@hong.com

In [198]:
# 1월생인 데이터
member = pd.read_csv('data/ch11_member.csv', comment='#', parse_dates=['Birth'])
member[member['Birth'].dt.month==1]

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [202]:
# 1월생이면서 서울시인 데이터
member[(member.Birth.dt.month==1) & member.Address.str.startswith('서울시')]

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [199]:
member

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구 1999-01-30

In [201]:
member.loc[[2,4], 'Email'] = np.nan
member

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구 1999-12-01
2  홍길남   21            NaN  서울시 강동구 1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구 1999-05-01
4  홍길중   23            NaN   부산시 중구 1999-01-30

In [203]:
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Age      5 non-null      int64
 2   Email    3 non-null      object
 3   Address  5 non-null      object
 4   Birth    5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 328.0+ bytes

In [204]:
member.isna()

    Name    Age  Email  Address  Birth
0  False  False  False    False  False
1  False  False  False    False  False
2  False  False   True    False  False
3  False  False  False    False  False
4  False  False   True    False  False

In [205]:
False + False + False

0

In [206]:
True + True + False

2

In [207]:
# 각 열의 결측치 갯수
member.isna().sum()

Name       0
Age        0
Email      2
Address    0
Birth      0
dtype: int64

In [212]:
# Email이 결측치인 행
member[member['Email'].isna()]

  Name  Age Email  Address      Birth
2  홍길남   21   NaN  서울시 강동구 1999-11-01
4  홍길중   23   NaN   부산시 중구 1999-01-30

※ 데이터 프레임의 부분 데이터 조회 방법
- df[열이름] - 특정 열의 모든 행 조회
- df[조건]   - 조건에 맞는 행의 모든 열 조회
- df.loc[행이름, 열이름] : 행이름과 열이름으로 조회
    * 행이름 자리에 조건 가능
    * 행이름, 열이름 자리에 list, 슬라이싱
    * 열이름 생략시 모든 열
- df.iloc[행번호, 열번호] : 번호로 조회
    * 행번호, 열번호 자리에 list, 슬라이싱
    * 열번호 생략시 모든 열

In [214]:
import seaborn as sns
iris = sns.load_dataset('iris')
#iris.head()
iris.iloc[::50]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica

In [216]:
# 1. sepal_length 열만 출력
iris['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [252]:
# 2. 0~10행까지 마지막 열을 제외한 데이터 (loc, iloc)
iris.loc[0:10, 'sepal_length':'petal_width']
iris.iloc[0:11, :-1]

    sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
5            5.4          3.9           1.7          0.4
6            4.6          3.4           1.4          0.3
7            5.0          3.4           1.5          0.2
8            4.4          2.9           1.4          0.2
9            4.9          3.1           1.5          0.1
10           5.4          3.7           1.5          0.2

In [254]:
# 3. 3~10 행중에 'sepal_length'와 'petal_length' 열만 (loc, iloc)
iris.loc[3:10, ['sepal_length','petal_length']]
iris.iloc[3:11, [0,2]]

    sepal_length  petal_length
3            4.6           1.5
4            5.0           1.4
5            5.4           1.7
6            4.6           1.4
7            5.0           1.5
8            4.4           1.4
9            4.9           1.5
10           5.4           1.5

In [255]:
# 4. 0번째, 50번째, 100번째 행의 모든 열 (loc, iloc)
iris.loc[[0, 50, 100], :]
iris.iloc[:101:50]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
100           6.3          3.3           6.0          2.5   virginica

In [259]:
# 5. 0번째, 25, 50번째, 75번, 100번째, 125번째 행의 petal_length와 petal_width (loc, iloc)
iris.loc[[0,25,50,75,100], ['petal_length', 'petal_width']]
iris.iloc[:126:25, 2:-1]

     petal_length  petal_width
0             1.4          0.2
25            1.6          0.2
50            4.7          1.4
75            4.4          1.4
100           6.0          2.5
125           6.0          1.8

In [263]:
# 6. species가 versicolor인 데이터의 모든 열
iris[iris.species=='versicolor']

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

In [237]:
# 7. species가 setosa인 데이터 최초 5개 행만 출력
iris[iris['species'].str.contains('setosa')]
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [262]:
# 8. sepal_length가 6.5이상인 데이터 최초 5개 행만 출력
iris[iris['sepal_length']>=6.5]
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [240]:
# 9. sepal_length가 7.2이상인 데이터의 'sepal_length'와 'sepal_width'와 'petal_length'
iris.loc[iris['sepal_length']>=7.2, 'sepal_length':'petal_length']

     sepal_length  sepal_width  petal_length
105           7.6          3.0           6.6
107           7.3          2.9           6.3
109           7.2          3.6           6.1
117           7.7          3.8           6.7
118           7.7          2.6           6.9
122           7.7          2.8           6.7
125           7.2          3.2           6.0
129           7.2          3.0           5.8
130           7.4          2.8           6.1
131           7.9          3.8           6.4
135           7.7          3.0           6.1

In [265]:
# 10. versicolor종중에서 sepal_length가 6.5보다 큰 데이터의 모든 열
iris[(iris['species'] == 'versicolor') & (iris['sepal_length']>6.5)]

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
52           6.9          3.1           4.9          1.5  versicolor
58           6.6          2.9           4.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
86           6.7          3.1           4.7          1.5  versicolor

# 데이터 삭제 및 추가
## 데이터 프레임의 요소 삭제
- df.drop(열이름이나 행이름, axis) : axis=0일때는 행삭제, axis-1일때는 열삭제

In [266]:
member = pd.read_csv('data/ch11_member.csv', comment='#')
member.index = ['동', '서', '남', '북', '중']
member

  Name  Age          Email  Address       Birth
동  홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
서  홍길서   30   seo@hong.com   서울시 중구  1999-12-01
남  홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
북  홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
중  홍길중   23   mid@hong.com   부산시 중구  1999-01-30