In [4]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

In [1]:
import pandas as pd

In [6]:
names = ['민수','영희','철수','지민']
math_score = [85, 90, 78, 95]
s_math = pd.DataFrame({'names':names, 'math_score':math_score})
s_math

  names  math_score
0    민수          85
1    영희          90
2    철수          78
3    지민          95

In [11]:
d = {'영어':[90,80,85,92], '과학':[88,95,76,89]}
df_score = pd.DataFrame(d, index=names)
df_score

    영어  과학
민수  90  88
영희  80  95
철수  85  76
지민  92  89